#Dockerfile for the node server services
FROM node:20-alpine

RUN npm install -g nodemon

WORKDIR /invoiceprint_backend_app

COPY . .

RUN npm install

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]
